### PR TITLE
Added projects section

### PR DESCRIPTION
**Pull request by SudhansuuRanjan**

### CODE REVIEW

**Comment by SudhansuuRanjan** [comment]
Merge this pull request !!!
There are no conflicts and I have also checked the full app and it also does not disturb any other CSS property on any other page.

**Comment by ShivamTyagi12345** [comment]
there are conflicting files

**Comment by SudhansuuRanjan** [comment]
> there are conflicting files @SudhansuuRanjan .Please try and resolve


Resolved!!!!

**Comment by ShivamTyagi12345** [comment]
// Pr under review

**Pull request closed without merging**
